export enum ItemStatus {
  AVAILABLE = 'Available',
  RENTED = 'Rented',
  MAINTENANCE = 'Maintenance',
  LOST = 'Lost'
}

export interface InventoryItem {
  id: string;
  model: string;
  serialNumber: string;
  dailyRate: number;
  status: ItemStatus;
  purchaseValue: number; // For accounting depreciation if we wanted to go deep
}

export enum RentalStatus {
  ACTIVE = 'Active',
  COMPLETED = 'Completed',
  OVERDUE = 'Overdue'
}

export interface RentalTransaction {
  id: string;
  itemId: string;
  customerName: string;
  customerNik: string; // ID number
  startDate: string; // ISO date
  endDate: string; // ISO date
  actualReturnDate?: string;
  totalCost: number;
  status: RentalStatus;
  agreementText?: string; // Generated by AI
}

export interface FinancialMetric {
  date: string;
  revenue: number;
  expenses: number;
}